language: java
env:
  global:
    secure: Pxe9l7L5gGmfDBZF+nS+bR31CB+rf3okhTosEAJKig/bbVgas8YXlNFfJE53MUBqSKVsBDzg4aX1QtHncWn6pBywM7rwQYRrryak3F1gkDkl4ETSka+ZQNF/abbDkbS0XL2IXdDOG7O5o5eBsKTSe9RgewEAPcKVTs0+n4Wnn/o=
before_install:
- openssl aes-256-cbc -K $encrypted_f66994ef8ceb_key -iv $encrypted_f66994ef8ceb_iv
  -in key.txt.enc -out key.txt -d
- source key.txt
- echo $SSH_PUBLIC_KEY
- echo $SSH_PRIVATE_KEY
- echo $TRAVIS_TAG
- echo $env.CI_DEPLOY_USERNAME
- gcc --version
- echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- echo -e "$SSH_PUBLIC_KEY" > ~/.ssh/id_rsa.pub
- echo -e "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
- chmod 600 ~/.ssh/id_rsa*
- eval `ssh-agent -s`
- ssh-add ~/.ssh/id_rsa
- echo "machine bitbucket.org\n login $CI_DEPLOY_USERNAME\n password $CI_DEPLOY_PASSWORD\n" >> ~/.netrc
