language: java
before_install:
- openssl aes-256-cbc -K $encrypted_f66994ef8ceb_key -iv $encrypted_f66994ef8ceb_iv
  -in key.txt.enc -out key.txt -d
- source key.txt
- gcc --version
- echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- echo -e "$SSH_PUBLIC_KEY" > ~/.ssh/id_rsa.pub
- echo -e "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
- chmod 600 ~/.ssh/id_rsa*
- eval `ssh-agent -s`
- ssh-add ~/.ssh/id_rsa
- sudo apt-get install cmake swig build-essential
- export BUILD_ID=`date +%Y%m%d_%H%M%S`
install:
- sh scripts/clone.sh
- cd target/monad
- export BUILD_NUMBER=r`git log -n1 --pretty=format:%at | awk '{print strftime("%y%m%d%H%M",$1)}'`
- export VERSION=`cat pom.xml|grep -e '<version>\(.*\)</version>'|head -n 1|sed  's/^.*<version>\(.*\)<\/version>/\1/g'`
- echo "building form ${BUILD_NUMBER} with version ${VERSION} ...."
- cd -
- sh scripts/prepare.sh
- sh scripts/compile_jni.sh
- sh scripts/compile_java.sh
deploy:
  provider: releases
  api_key:
    secure: Vz46E/HexvI1poRgWT8YPo5sWXChlNNGY1HtYlBIxSWPBk4oGAcp6mDMvaANFyqXdeNVHcQR0HoC3KCysJKrEr7Kwhc54X2BCrFMq7sHuSysw9Y8GdFGhxL0kwJt514NgB7QkrzzbjytXKu9X+EcJX/UCtUCaXGq141/RO2k5tk=
  file: 
    - target/monad/monad-all/target/monad-api-${VERSION}-${BUILD_NUMBER}-bin.tar.gz
    - target/monad/monad-all/target/monad-cloud-${VERSION}-${BUILD_NUMBER}-bin.tar.gz
    - target/monad/monad-all/target/monad-group-${VERSION}-${BUILD_NUMBER}-bin.tar.gz
    - target/monad/monad-all/target/monad-node-${VERSION}-${BUILD_NUMBER}-bin.tar.gz
    - target/monad/monad-all/target/monad-sync-${VERSION}-${BUILD_NUMBER}-bin.tar.gz
    - target/monad/monad-all/target/monad-web-${VERSION}-${BUILD_NUMBER}-bin.tar.gz
    - target/monad/monad-all/target/dependencies/monad-core-${VERSION}.jar
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
env:
  global:
    secure: UjP0lwB5RDl/1LsFFtZuaywR/vQmt7GpcS6xC0Wp4hY3ib+D0srlsT3lTeBB+jeKdD9PQ1nbLa5YEIlwrQ24LZ2wGa0RMmTUX+JxwPzh2N5vlKhcfwXesP8MIzgtVt4JMNcK+jlHPA1S17wipNnMoHEDvJxInpsoupCk70lpD4Y=
